name: everyday_env
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - aiodns=3.6.1
  - aiohappyeyeballs=2.6.2
  - aiohttp=3.14.1
  - aiosignal=1.4.0
  - alabaster=1.0.0
  - alsa-lib=1.2.15.3
  - anyio=4.12.1
  - argon2-cffi=25.1.0
  - argon2-cffi-bindings=25.1.0
  - arrow=1.4.0
  - astroid=4.0.3
  - asttokens=3.0.1
  - async-lru=2.3.0
  - asyncssh=2.21.1
  - attrs=26.1.0
  - autopep8=2.0.4
  - babel=2.17.0
  - backports.tarfile=1.2.0
  - bcrypt=5.0.0
  - beautifulsoup4=4.15.0
  - binaryornot=0.6.0
  - black=26.5.1
  - bleach=6.4.0
  - brotlicffi=1.2.0.0
  - bzip2=1.0.8
  - c-ares=1.34.7
  - ca-certificates=2026.7.16
  - cairo=1.18.4
  - cattrs=26.1.0
  - certifi=2026.6.17
  - cffi=2.1.0
  - chardet=5.2.0
  - charset-normalizer=3.4.7
  - click=8.4.1
  - cloudpickle=3.1.2
  - comm=0.2.3
  - cookiecutter=2.7.1
  - cryptography=49.0.0
  - cyrus-sasl=2.1.28
  - dbus=1.16.2
  - debugpy=1.8.21
  - decorator=5.3.1
  - defusedxml=0.7.1
  - diff-match-patch=20200713
  - dill=0.4.1
  - docstring-to-markdown=0.17
  - docutils=0.21.2
  - executing=2.2.1
  - expat=2.8.2
  - flake8=7.1.1
  - fontconfig=2.17.1
  - freetype=2.14.1
  - frozenlist=1.8.0
  - graphite2=1.3.15
  - h11=0.16.0
  - harfbuzz=12.3.0
  - httpcore=1.0.9
  - httpx=0.28.1
  - icu=78.3
  - idna=3.18
  - imagesize=1.4.1
  - importlib-metadata=8.7.1
  - inflection=0.5.1
  - intervaltree=3.2.1
  - ipykernel=6.31.0
  - ipython=9.15.0
  - ipython_pygments_lexers=1.1.1
  - isort=8.0.1
  - jaraco.classes=3.4.0
  - jaraco.context=6.1.0
  - jaraco.functools=4.4.0
  - jedi=0.19.2
  - jeepney=0.7.1
  - jellyfish=1.2.1
  - jinja2=3.1.6
  - json5=0.12.1
  - jsonschema=4.25.1
  - jsonschema-specifications=2025.9.1
  - jupyter-lsp=2.3.0
  - jupyter_client=8.9.1
  - jupyter_core=5.9.1
  - jupyter_events=0.12.1
  - jupyter_server=2.20.0
  - jupyter_server_terminals=0.5.4
  - jupyterlab=4.5.9
  - jupyterlab_pygments=0.3.0
  - jupyterlab_server=2.28.0
  - keyring=25.7.0
  - lcms2=2.19.1
  - ld_impl_linux-64=2.44
  - lerc=4.1.0
  - libabseil=20260107.0
  - libcups=2.4.15
  - libdeflate=1.22
  - libdrm=2.4.124
  - libegl=1.7.0
  - libevent=2.1.12
  - libexpat=2.8.2
  - libffi=3.4.8
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgl=1.7.0
  - libglib=2.86.3
  - libglvnd=1.7.0
  - libglx=1.7.0
  - libiconv=1.18
  - libjpeg-turbo=3.1.3
  - libkrb5=1.22.2
  - libllvm21=21.1.8
  - libnsl=2.0.0
  - libopengl=1.7.0
  - libopenjpeg=2.5.4
  - libopus=1.6.1
  - libpciaccess=0.18
  - libpng=1.6.56
  - libpq=17.10
  - libre2-11=2025.11.05
  - libsodium=1.0.21
  - libspatialindex=2.1.0
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libtiff=4.7.1
  - libuuid=1.41.5
  - libuv=1.52.0
  - libvpx=1.16.0
  - libwebp-base=1.6.0
  - libxcb=1.17.0
  - libxkbcommon=1.13.1
  - libxkbfile=1.1.0
  - libxml2=2.14.6
  - libxslt=1.1.43
  - libzlib=1.3.2
  - lmdb=0.9.31
  - lsprotocol=2025.0.0
  - lz4-c=1.9.4
  - markdown-it-py=4.0.0
  - markupsafe=3.0.3
  - matplotlib-inline=0.2.1
  - mccabe=0.7.0
  - mdurl=0.1.2
  - mesalib=25.1.5
  - mistune=3.3.3
  - more-itertools=11.0.2
  - multidict=6.7.1
  - mypy_extensions=1.1.0
  - mysql-common=9.3.0
  - mysql-libs=9.3.0
  - nbclient=0.11.0
  - nbconvert=7.17.1
  - nbconvert-core=7.17.1
  - nbconvert-pandoc=7.17.1
  - nbformat=5.10.4
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - notebook=7.5.7
  - notebook-shim=0.2.4
  - nspr=4.39
  - nss=3.121
  - numpydoc=1.10.0
  - openldap=2.6.12
  - openssl=3.5.7
  - overrides=7.7.0
  - packaging=26.0
  - pandoc=3.8
  - pandocfilters=1.5.1
  - parso=0.8.7
  - pathspec=1.0.4
  - pcre2=10.46
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pip=26.1.2
  - pixman=0.46.4
  - platformdirs=4.9.4
  - pluggy=1.6.0
  - prometheus_client=0.24.1
  - prompt-toolkit=3.0.52
  - prompt_toolkit=3.0.52
  - propcache=0.4.1
  - psutil=7.0.0
  - pthread-stubs=0.3
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pycares=4.10.0
  - pycodestyle=2.12.1
  - pycparser=3.0
  - pydocstyle=6.3.0
  - pyflakes=3.2.0
  - pygithub=2.9.1
  - pygments=2.20.0
  - pyjwt=2.13.0
  - pylint=4.0.6
  - pylint-venv=3.0.3
  - pyls-spyder=0.4.0
  - pynacl=1.6.2
  - pyqt=6.11.0
  - pyqt6-sip=13.11.1
  - pyqtwebengine=6.11.0
  - pysocks=1.7.1
  - python=3.11.15
  - python-dateutil=2.9.0post0
  - python-fastjsonschema=2.21.2
  - python-json-logger=4.0.0
  - python-lsp-black=2.0.0
  - python-lsp-jsonrpc=1.1.2
  - python-lsp-ruff=2.3.0
  - python-lsp-server=1.14.0
  - python-slugify=8.0.4
  - python-tzdata=2026.2
  - pytokens=0.4.1
  - pytoolconfig=1.3.1
  - pyuca=1.2
  - pyxdg=0.28
  - pyyaml=6.0.3
  - pyzmq=27.1.0
  - qdarkstyle=3.2.3
  - qstylizer=0.2.4
  - qtawesome=1.4.2
  - qtbase=6.11.0
  - qtconsole=5.7.2
  - qtdeclarative=6.11.0
  - qtpy=2.4.3
  - qtsvg=6.11.0
  - qttools=6.11.0
  - qtwayland=6.11.0
  - qtwebchannel=6.11.0
  - qtwebengine=6.11.0
  - qtwebsockets=6.11.0
  - re2=2025.11.05
  - readline=8.3
  - referencing=0.37.0
  - requests=2.34.2
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rich=15.0.0
  - roman-numerals-py=3.1.0
  - rope=1.14.0
  - rpds-py=0.28.0
  - rtree=1.4.1
  - ruff=0.15.1
  - secretstorage=3.5.0
  - send2trash=1.8.3
  - setuptools=83.0.0
  - sip=6.15.1
  - six=1.17.0
  - snappy=1.2.2
  - snowballstemmer=3.1.1
  - sortedcontainers=2.4.0
  - soupsieve=2.8.4
  - sphinx=8.2.3
  - sphinxcontrib-applehelp=2.0.0
  - sphinxcontrib-devhelp=2.0.0
  - sphinxcontrib-htmlhelp=2.1.0
  - sphinxcontrib-jsmath=1.0.1
  - sphinxcontrib-qthelp=2.0.0
  - sphinxcontrib-serializinghtml=2.0.0
  - spirv-tools=2026.1
  - spyder=6.1.5
  - spyder-kernels=3.1.5
  - sqlite=3.53.2
  - stack_data=0.6.3
  - superqt=0.8.1
  - terminado=0.18.1
  - text-unidecode=1.3
  - textdistance=4.6.3
  - three-merge=0.1.1
  - tinycss2=1.5.1
  - tk=8.6.15
  - tomlkit=0.13.3
  - tornado=6.5.7
  - traitlets=5.15.0
  - typing-extensions=4.16.0
  - typing_extensions=4.16.0
  - tzdata=2026c
  - ujson=5.13.0
  - urllib3=2.7.0
  - uvloop=0.22.1
  - watchdog=6.0.0
  - wayland=1.24.0
  - wcwidth=0.8.2
  - webencodings=0.5.1
  - websocket-client=1.8.0
  - whatthepatch=1.0.7
  - wheel=0.47.0
  - wurlitzer=3.1.1
  - xcb-util=0.4.1
  - xcb-util-cursor=0.1.5
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.1
  - xcb-util-renderutil=0.3.10
  - xcb-util-wm=0.4.2
  - xkeyboard-config=2.44
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.6
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxcomposite=0.4.6
  - xorg-libxdamage=1.1.6
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxfixes=6.0.1
  - xorg-libxi=1.8.2
  - xorg-libxrandr=1.5.4
  - xorg-libxrender=0.9.12
  - xorg-libxshmfence=1.3.3
  - xorg-libxtst=1.2.5
  - xorg-libxxf86vm=1.1.6
  - xorg-xorgproto=2024.1
  - xz=5.8.2
  - yaml=0.2.5
  - yapf=0.43.0
  - yarl=1.24.2
  - zeromq=4.3.5
  - zipp=3.23.0
  - zlib=1.3.2
  - zstd=1.5.7
  - pip:
      - affine==2.4.0
      - cartopy==0.25.0
      - cftime==1.6.5
      - click-plugins==1.1.1.2
      - cligj==0.7.2
      - contourpy==1.3.3
      - cramjam==2.11.0
      - cycler==0.12.1
      - dask==2026.7.1
      - donfig==0.8.1.post1
      - fastparquet==2026.5.0
      - fiona==1.10.1
      - fonttools==4.63.0
      - fsspec==2026.6.0
      - geopandas==1.1.4
      - google-crc32c==1.8.0
      - h5netcdf==1.8.1
      - h5py==3.16.0
      - kiwisolver==1.5.0
      - locket==1.0.0
      - lxml==6.1.1
      - matplotlib==3.11.1
      - netcdf4==1.7.4
      - numcodecs==0.16.5
      - numpy==2.4.6
      - pandas==3.0.3
      - partd==1.4.2
      - pillow==12.3.0
      - pyogrio==0.13.0
      - pyparsing==3.3.2
      - pyproj==3.7.2
      - pyshp==3.1.6
      - python-docx==1.2.0
      - rasterio==1.4.4
      - rioxarray==0.19.0
      - scipy==1.17.1
      - shapely==2.1.2
      - toolz==1.1.0
      - xarray==2026.7.0
      - zarr==3.1.6
